# Generated by Django 3.2.18 on 2023-03-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID',
                )),
                ('text', models.TextField(
                    verbose_name='text',
                )),
                ('created_on', models.DateTimeField(
                    auto_now_add=True,
                )),
                ('email', models.EmailField(
                    max_length=254,
                    verbose_name='email',
                )),
            ],
        ),
    ]
