# Generated by Django 3.2.18 on 2023-03-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback',
            options={
                'verbose_name': 'feedback form',
                'verbose_name_plural': 'feedbacks forms',
            },
        ),
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.CharField(
                choices=[
                    ('received', 'Received'),
                    ('in_processing', 'In processing'),
                    ('answer_given', 'The answer is given'),
                ],
                default='received',
                max_length=32,
                verbose_name='status',
            ),
        ),
    ]
