# Generated by Django 3.2.18 on 2023-03-13 17:41

import django.db.models.deletion
from django.db import migrations, models

from server.apps.core.models import file


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackFile',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID',
                )),
                ('file', models.FileField(
                    upload_to=file.get_upload_to,
                    verbose_name='uploaded file',
                )),
                ('feedback', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='feedback.feedback',
                    verbose_name='feedback',
                )),
            ],
            options={
                'verbose_name': 'feedback file',
                'verbose_name_plural': 'feedbacks files',
            },
        ),
        migrations.AddField(
            model_name='feedback',
            name='files',
            field=models.ManyToManyField(
                related_name='files',
                to='feedback.FeedbackFile',
                verbose_name='files',
            ),
        ),
    ]
