# Generated by Django 3.2.18 on 2023-03-14 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackPersonalData',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID',
                )),
                ('email', models.EmailField(
                    max_length=254,
                    unique=True,
                    verbose_name='email',
                )),
            ],
            options={
                'verbose_name': 'personal data',
                'verbose_name_plural': 'personal data',
            },
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='email',
        ),
        migrations.AddField(
            model_name='feedback',
            name='personal_data',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='feedback.feedbackpersonaldata',
                verbose_name='personal data',
            ),
        ),
    ]
