# Generated by Django 3.2.17 on 2023-02-21 13:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import server.apps.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogCategory',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Id')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('slug', models.SlugField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator('^[0-9-_a-zA-Z]+$')])),
                ('weight', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(32767)], verbose_name='Вес')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='CatalogTag',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Id')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Id')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('text', models.TextField(validators=[server.apps.core.validators.is_contains], verbose_name='Описание')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.catalogcategory', verbose_name='Категории')),
                ('tags', models.ManyToManyField(to='catalog.CatalogTag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
