# Generated by Django 3.2.17 on 2023-02-23 16:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import server.apps.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogcategory',
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='catalogitem',
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.AlterModelOptions(
            name='catalogtag',
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AddField(
            model_name='catalogcategory',
            name='normalized_name',
            field=models.CharField(
                editable=False,
                max_length=150,
                null=True,
                unique=True,
                verbose_name='Normalized Name',
            ),
        ),
        migrations.AddField(
            model_name='catalogtag',
            name='normalized_name',
            field=models.CharField(
                editable=False,
                max_length=150,
                null=True,
                unique=True,
                verbose_name='Normalized Name',
            ),
        ),
        migrations.AlterField(
            model_name='catalogcategory',
            name='is_published',
            field=models.BooleanField(
                default=True,
                verbose_name='Published',
            ),
        ),
        migrations.AlterField(
            model_name='catalogcategory',
            name='name',
            field=models.CharField(
                help_text='Maximum length 150',
                max_length=150,
                verbose_name='Name',
            ),
        ),
        migrations.AlterField(
            model_name='catalogcategory',
            name='weight',
            field=models.IntegerField(
                default=100,
                help_text='Weight must be greater than 0 and less than 32767',
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(32767),
                ],
                verbose_name='Weight',
            ),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='category',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='catalog.catalogcategory',
                verbose_name='Categories',
            ),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='is_published',
            field=models.BooleanField(
                default=True,
                verbose_name='Published',
            ),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='name',
            field=models.CharField(
                help_text='Maximum length 150',
                max_length=150,
                verbose_name='Name',
            ),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='tags',
            field=models.ManyToManyField(
                to='catalog.CatalogTag',
                verbose_name='Tags',
            ),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='text',
            field=models.TextField(
                help_text=(
                    'The description should be more than 2x words ' +
                    'and contain the words "превосходно, роскошно"'
                ),
                validators=[
                    server.apps.core.validators.ContainsValidator,
                ],
                verbose_name='Description',
            ),
        ),
        migrations.AlterField(
            model_name='catalogtag',
            name='is_published',
            field=models.BooleanField(
                default=True,
                verbose_name='Published',
            ),
        ),
        migrations.AlterField(
            model_name='catalogtag',
            name='name',
            field=models.CharField(
                help_text='Maximum length 150',
                max_length=150,
                verbose_name='Name',
            ),
        ),
    ]
