# Generated by Django 3.2.17 on 2023-02-25 14:44

from django.db import migrations, models

import server.apps.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_localization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='text',
            field=models.TextField(
                help_text=(
                    'The description should be more than 2x words and ' +
                    'contain the words "превосходно, роскошно"'
                ),
                validators=[
                    server.apps.core.validators.is_contains,
                ],
                verbose_name='description',
            ),
        ),
        migrations.AlterModelTable(
            name='catalogcategory',
            table='catalog_category',
        ),
        migrations.AlterModelTable(
            name='catalogitem',
            table='catalog_item',
        ),
        migrations.AlterModelTable(
            name='catalogtag',
            table='catalog_tag',
        ),
    ]
