# Generated by Django 3.2.17 on 2023-02-26 19:38

import django.db.models.deletion
import sorl.thumbnail.fields
from django.db import migrations, models

import server.apps.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_change_table_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='main_image',
            field=sorl.thumbnail.fields.ImageField(
                null=True,
                upload_to='catalog_images',
                verbose_name='image',
            ),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='text',
            field=models.TextField(
                help_text=(
                    'The description should be more than 2x words ' +
                    'and contain the words "превосходно, роскошно"'
                ),
                validators=[
                    server.apps.core.validators.ContainsValidator,
                ],
                verbose_name='description',
            ),
        ),
        migrations.CreateModel(
            name='ImageItem',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID',
                )),
                ('image', sorl.thumbnail.fields.ImageField(
                    upload_to='images',
                    verbose_name='image',
                )),
                ('item', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    to='catalog.catalogitem',
                )),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'db_table': 'images',
            },
        ),
    ]
