# Generated by Django 3.2.17 on 2023-02-28 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageitem',
            old_name='item',
            new_name='product',
        ),
        migrations.AlterModelTable(
            name='imageitem',
            table='catalog_images',
        ),
    ]
