# Generated by Django 3.2.18 on 2023-03-04 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_image_mixin'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='is_on_main',
            field=models.BooleanField(
                default=False,
                verbose_name='is on main',
            ),
        ),
    ]
