# Generated by Django 3.2.18 on 2023-03-08 14:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_add_many_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogcategory',
            options={
                'ordering': ('name',),
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True,
            ),
        ),
    ]
