# Generated by Django 3.2.18 on 2023-03-18 11:30

from django.db import migrations, models

import server.apps.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='text',
            field=models.TextField(
                help_text=(
                    'The description should be more than 2x words and ' +
                    'contain the words "превосходно, роскошно"'
                ),
                validators=[
                    server.apps.core.validators.ContainsValidator(
                        'превосходно', 'роскошно',
                    ),
                ],
                verbose_name='description',
            ),
        ),
    ]
