# Generated by Django 3.2.18 on 2023-03-19 18:07

import django.db.models.deletion
import sorl.thumbnail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID',
                )),
                ('image', sorl.thumbnail.fields.ImageField(
                    null=True,
                    upload_to='images',
                    verbose_name='image',
                )),
                ('birthday', models.DateField(
                    blank=True,
                    null=True,
                    verbose_name='birthday',
                )),
                ('coffee_count', models.IntegerField(
                    default=0,
                    verbose_name='coffe count',
                )),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='user',
                )),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
