# Generated by Django 3.2.18 on 2023-03-23 18:00

from django.db import migrations
import server.apps.users.logic.queries.user


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWithProfile',
            fields=[
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', server.apps.users.logic.queries.user.UserWithProfileManager()),
            ],
        ),
    ]
